server:
  port: 18088
  servlet:
    context-path: /future

spring:
  application:
    name: back
  datasource:
    url: jdbc:mariadb://{IP}}:{PORT}/test_db
    username: {ID}
    password: {PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: update

logging:
  config: classpath:log4j2.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # API 정렬 순서 path > query > body > response
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**
  api-docs:
    path: /api-docs/json
  cache:
    disabled: true

gemini:
  model: gemini-1.5-flash
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=
    key: {PUT_GEMINI_KEY}
